### ISSUE TITLE
horizon-card not working inside custom:collapsable-cards

### ISSUE THREAD

**Issue by mleiber** [rejuvenate/lovelace-horizon-card#112]
using the horizon-card inside a `custom:collapsable-cards ` (https://github.com/RossMcMillan92/lovelace-collapsable-cards) leads to a blank card. Example:

```
 - type: 'custom:collapsable-cards'
   title: "Sunrise/Sunset"
   cards:
    - type: 'custom:horizon-card'
      #title: Horizon Card
      moon: true
      refresh_period: 60
      ...
```

results in a blank card.
