### ISSUE TITLE
Feature request: Tide graph

### ISSUE THREAD

**Issue by danieljowitsch** [rejuvenate/lovelace-horizon-card#165]
Not celestial bodies but definitely related I’m wondering if a graph can be added showing high and low tides during any given day? I have low and high tide entities from our weather app (MetService New Zealand), so data could be taken from there if need be.

**Comment by kattcrazy** [comment]
Would also love this!
I made a makeshift one but it only shows past tides. Code below in case interested.

Card
```
type: custom:mini-graph-card
name: 24hr Temperature
icon: mdi:temperature-celsius
hours_to_show: 24
line_width: 2
hour24: false
entities:
  - entity: sensor.current_tide
    name: Current tide
    color: "#89CFF0"
    show_legend_state: true
show:
  icon: false
  name: false
  state: false
  labels: false
  points: false
  graph: line
  fill: false
  legend: true
  average: false
  extrema: false
  labels_secondary: false
  loading_indicator: true
grid_options:
  columns: 12
  rows: 2.1
card_mod:
  style: |
    ha-card {
      position: relative;
    }
    ha-card .graph {
      margin-top: 2px !important;
      margin-bottom: 0 !important;
    }
    /* Add current tide as text below the graph */
    ha-card::after {
      content: "Current tide: " var(--state);
      display: block;
      color: white;
      text-align: center;
      margin-top: 3px;
    }
    /* Dynamically update the variable with entity state */
    ha-card {
      --state: "{{ states('sensor.current_tide') }}m";
    }

```

Sensor (requires tidespy API)
```
  - sensor:
      name: Current Tide
      command: python3 -c "import requests,datetime,zoneinfo; now=datetime.datetime.now(zoneinfo.ZoneInfo('Pacific/Auckland')); data=requests.get(f'https://tidespy.com/api/tideturns?pn=3141&unit=m&start={now:%Y%m%d}&days=1&key=ncWYgTPaDCkHKuGrt0NxlA8d9MhsFi4Q').json(); turns=data.get('Turns',[]); now_min=now.hour*60+now.minute; prev=next((t for t in reversed(turns) if t['Minute']<=now_min),turns[0] if turns else None); nxt=next((t for t in turns if t['Minute']>now_min),turns[-1] if turns else None); h=float(prev['Height'])+(now_min-prev['Minute'])/(nxt['Minute']-prev['Minute'])*(float(nxt['Height'])-float(prev['Height'])) if prev and nxt and nxt['Minute']!=prev['Minute'] else (float(prev['Height']) if prev else None); print(round(h,2) if h is not None else 'No tide data')"
      scan_interval: 900
```
