### ISSUE TITLE
Time not displayed in different timezone

### ISSUE THREAD

**Issue by thoughtgap** [rejuvenate/lovelace-horizon-card#166]
Hello, thanks for providing this card.

My use case is to display the local situation at specified coordinates.
Card configuration:

```yaml
type: custom:horizon-card
latitude: 27.714
longitude: 86.736
time_zone: Asia/Kathmandu
language: en
````

The times are still displayed in my local time (CET).

<img width="1074" alt="Image" src="https://github.com/user-attachments/assets/ff755edf-1d8c-4d16-b4f2-134e16f3dbda" />

For reference: It was 11:27 AM CET when I took the screenshot, 16:12 Asia/Kathmandu time.

How can I display in timezone specified? It seems that `time_zone` attribute is ignored.

Thanks.
