### ISSUE TITLE
Label error with moon phase text

### ISSUE THREAD

**Issue by gibbonsr4** [rejuvenate/lovelace-horizon-card#167]
I noticed the following issue across multiple state values for the the Moon phase.

<img width="468" alt="Image" src="https://github.com/user-attachments/assets/77a5a0d5-4058-492d-a393-a62ec08622f7" />

(Edited to include YAML below)
```
type: custom:horizon-card
moon: true
refresh_period: 15
fields:
  sunrise: true
  sunset: true
  moonrise: true
  moonset: true
  moon_phase: true
```

This issue has persisted across different phases.  And I have also uninstalled and reinstalled the HACS card (along with restarts and cache clears at every step of the way).

Running the most recent version of HA and HAOS (2025.3.0), but I also had this issue on the last few versions of 2025.2.x, not sure about 2025.1.x.

Any ideas?  Let me know how I can help.

Thanks!
Ryan
