### ISSUE TITLE
Card may not be displayed in a dashboard edit mode

### ISSUE THREAD

**Issue by ildar170975** [rejuvenate/lovelace-horizon-card#57]
0.9.1
2023.7.0

In Edit mode, the card is not displayed:

![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/71872483/07a61180-1d44-46d6-a7f7-198df21c1212)

```
type: custom:horizon-card
```

It is displayed in Editor:

![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/71872483/bf742754-98e1-48b2-a4a1-35266cf6c29c)

and in "non-Edit" mode:

![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/71872483/72ebe51d-466f-4755-b1bf-bbe2bce382da)

How to reproduce:
1. Open a view.
2. Select Edit mode.
3. Add a card.
4. Save the card.
5. Refresh the page.
6. The card is not displayed.

**Comment by ildar170975** [comment]
I guess I found exact conditions when the card may not be displayed:
```
  - theme: ''
    title: xxx
    path: xxx
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: history-graph
            entities:
              - sun.sun
      - type: custom:horizon-card
```
same as happened with `custom:windrose-card` - it also uses "canvas" element (https://github.com/aukedejong/lovelace-windrose-card/issues/39).
