### ISSUE TITLE
V1.0.0 not displaying new options

### ISSUE THREAD

**Issue by squirtbrnr** [rejuvenate/lovelace-horizon-card#61]
I updated the card through HACS.  I added the new config options to enable moon support and removed the old option for 24 hour time.  The card does not show the moon info and it reverted back to using 12 hour time.  I redownloaded it again, I cleared cache and logged back in and even tried another device and it still shows the old card and none of the moon options.

My v0.9.1 config:
```
      - type: custom:horizon-card
        fields:
          azimuth: true
          elevation: true
        use12hourClock: false
```

My v1.0.0 config:
```
      - type: custom:horizon-card
        moon: true
        fields:
          azimuth: true
          elevation: true
          moonrise: true
          moonset: true
          moon_phase: true
        time_format: 24
```

no matter how many times i refresh or clear cache, my card still looks like this:
![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/35356217/3e063476-047e-45f8-b289-078d9cb9d6f9)
