### ISSUE TITLE
Wrong sun position?

### ISSUE THREAD

**Issue by tjorim** [rejuvenate/lovelace-horizon-card#67]
Not sure but it seems a problem with AM/PM? See screenshots below, sun just went under but is already on the left?

![Screenshot_20230714-191708.png](https://github.com/rejuvenate/lovelace-horizon-card/assets/1294876/13ae59aa-c440-4ced-aaa1-ca2ad8c0909e)

![Screenshot_20230715-182751.png](https://github.com/rejuvenate/lovelace-horizon-card/assets/1294876/fabc141b-ef65-436f-87d0-5d161b20997e)

**Comment by tjorim** [comment]
To clarify I'm talking about the Pearl Valley one, here is the code snippet:

```
title: Pearl valley
type: custom:horizon-card
latitude: -33.82
longitude: 18.98
elevation: 120
fields:
  azimuth: true
  elevation: true
  moonrise: true
  moonset: true
  moon_phase: true
```
