### ISSUE TITLE
Incorrect Moon Position in Graphic (Southern Hemisphere Loc, flip=false)

### ISSUE THREAD

**Issue by AstroPhotoJay** [rejuvenate/lovelace-horizon-card#82]
As the name suggests... 

- I'm located in the southern hemisphere
- This issue only occurs when southern_flip=false.
- The moon textual information displayed in the card is correct.
- Correct location has been configured in HA settings

Screenshots

Left card: southern flip disabled. Right card: southern flip enabled
![image](https://github.com/rejuvenate/lovelace-horizon-card/assets/97019222/3b5746bb-d276-4051-be4a-6e6b3abbf5fe)

Card Configs

Left Card (incorrect display)
```
type: custom:horizon-card
moon: true
refresh_period: 60
fields:
  sunrise: true
  sunset: true
  dawn: true
  noon: true
  dusk: true
  azimuth: true
  sun_azimuth: true
  moon_azimuth: true
  elevation: false
  sun_elevation: true
  moon_elevation: true
  moonrise: true
  moonset: true
  moon_phase: true
southern_flip: false
```
Right Card (Correct Display)
```
type: custom:horizon-card
moon: true
refresh_period: 60
fields:
  sunrise: true
  sunset: true
  dawn: true
  noon: true
  dusk: true
  azimuth: true
  sun_azimuth: true
  moon_azimuth: true
  elevation: false
  sun_elevation: true
  moon_elevation: true
  moonrise: true
  moonset: true
  moon_phase: true
southern_flip: false
```
