### ISSUE TITLE
Wrong sunset time in card?

### ISSUE THREAD

**Issue by wigster** [rejuvenate/lovelace-horizon-card#86]
My current sun.sun state is:
```
next_dawn: 2023-09-27T04:20:06.460118+00:00
next_dusk: 2023-09-26T17:27:41.138746+00:00
next_midnight: 2023-09-26T22:53:18+00:00
next_noon: 2023-09-27T10:53:27+00:00
next_rising: 2023-09-27T04:53:21.657868+00:00
next_setting: 2023-09-26T16:54:31.506323+00:00
elevation: 37.64
azimuth: 195.27
rising: false
friendly_name: Sun
```
I am two hours ahead of UTC, so the sunset in the card should be at 18:54, but instead it is 18:58. The sunrise time is also two minutes out. Maybe there is some additional adjustment that the card does, but, in any case, we are past the autumnal equinox, so the day should be less than 12 hours.

<img width="350" alt="image" src="https://github.com/rejuvenate/lovelace-horizon-card/assets/10956987/5c810dd2-f9aa-4bfc-b3d5-8ec13386b9a7">

Here is my card's config:
```
type: custom:horizon-card
fields:
  elevation: true
  azimuth: true
  moonrise: true
  moonset: true
```
